// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `failed_event`, `is_text`, `map_event`

Future<List<MobileReceiveEvent>> checkPcmForHandshake({
  required List<int> pcm16Le,
  required int sampleRate,
}) => RustLib.instance.api.crateApiRxCheckPcmForHandshake(
  pcm16Le: pcm16Le,
  sampleRate: sampleRate,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RxSession>>
abstract class RxSession implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RxSession> newInstance({
    required int sampleRate,
    required String outputDir,
  }) => RustLib.instance.api.crateApiRxRxSessionNew(
    sampleRate: sampleRate,
    outputDir: outputDir,
  );

  Future<List<MobileReceiveEvent>> pushPcm16({required List<int> pcm16Le});
}
