// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TxSession>>
abstract class TxSession implements RustOpaqueInterface {
  Future<void> cancel();

  /// Build a transfer from bytes. `reliable` selects the slow but robust
  /// Robust-FSK link; otherwise the faster OFDM link is used (with FSK only for
  /// tiny inline chat frames, handled by the hybrid router transparently).
  static Future<TxSession> fromData({
    required String name,
    String? contentType,
    required List<int> data,
    required bool reliable,
  }) => RustLib.instance.api.crateApiTxTxSessionFromData(
    name: name,
    contentType: contentType,
    data: data,
    reliable: reliable,
  );

  /// Build a transfer from a file. `reliable` selects the slow but robust
  /// Robust-FSK link; otherwise the faster OFDM link is used.
  static Future<TxSession> fromFile({
    required String path,
    String? contentType,
    required bool reliable,
  }) => RustLib.instance.api.crateApiTxTxSessionFromFile(
    path: path,
    contentType: contentType,
    reliable: reliable,
  );

  Future<TxInfo> info();

  Future<TxChunk> nextPcmChunk({required int maxSamples});
}
