// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `samples_to_pcm16`

Future<Uint8List> handshakeRequestPcm({required BigInt id}) =>
    RustLib.instance.api.crateApiTxHandshakeRequestPcm(id: id);

Future<Uint8List> handshakeAckPcm({required BigInt id}) =>
    RustLib.instance.api.crateApiTxHandshakeAckPcm(id: id);

Future<Uint8List> endAckPcm({required BigInt id}) =>
    RustLib.instance.api.crateApiTxEndAckPcm(id: id);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TxSession>>
abstract class TxSession implements RustOpaqueInterface {
  Future<void> cancel();

  static Future<TxSession> fromData({
    required String name,
    String? contentType,
    required List<int> data,
  }) => RustLib.instance.api.crateApiTxTxSessionFromData(
    name: name,
    contentType: contentType,
    data: data,
  );

  static Future<TxSession> fromFile({
    required String path,
    String? contentType,
  }) => RustLib.instance.api.crateApiTxTxSessionFromFile(
    path: path,
    contentType: contentType,
  );

  Future<TxInfo> info();

  Future<TxChunk> nextPcmChunk({required int maxSamples});
}
