// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

class MobileReceiveEvent {
  final String kind;
  final String id;
  final String? name;
  final String? contentType;
  final String? path;
  final String? text;
  final String? message;
  final BigInt? originalSize;
  final int? completedGroups;
  final int? totalGroups;

  const MobileReceiveEvent({
    required this.kind,
    required this.id,
    this.name,
    this.contentType,
    this.path,
    this.text,
    this.message,
    this.originalSize,
    this.completedGroups,
    this.totalGroups,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      id.hashCode ^
      name.hashCode ^
      contentType.hashCode ^
      path.hashCode ^
      text.hashCode ^
      message.hashCode ^
      originalSize.hashCode ^
      completedGroups.hashCode ^
      totalGroups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileReceiveEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id &&
          name == other.name &&
          contentType == other.contentType &&
          path == other.path &&
          text == other.text &&
          message == other.message &&
          originalSize == other.originalSize &&
          completedGroups == other.completedGroups &&
          totalGroups == other.totalGroups;
}

class TxChunk {
  final Uint8List pcm16Le;
  final double progress;
  final int packetIndex;
  final int packetCount;
  final bool done;

  const TxChunk({
    required this.pcm16Le,
    required this.progress,
    required this.packetIndex,
    required this.packetCount,
    required this.done,
  });

  @override
  int get hashCode =>
      pcm16Le.hashCode ^
      progress.hashCode ^
      packetIndex.hashCode ^
      packetCount.hashCode ^
      done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxChunk &&
          runtimeType == other.runtimeType &&
          pcm16Le == other.pcm16Le &&
          progress == other.progress &&
          packetIndex == other.packetIndex &&
          packetCount == other.packetCount &&
          done == other.done;
}

class TxInfo {
  final String id;
  final String name;
  final String contentType;
  final BigInt originalSize;
  final BigInt encodedSize;
  final int packetCount;
  final double estimatedSeconds;

  const TxInfo({
    required this.id,
    required this.name,
    required this.contentType,
    required this.originalSize,
    required this.encodedSize,
    required this.packetCount,
    required this.estimatedSeconds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      contentType.hashCode ^
      originalSize.hashCode ^
      encodedSize.hashCode ^
      packetCount.hashCode ^
      estimatedSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          contentType == other.contentType &&
          originalSize == other.originalSize &&
          encodedSize == other.encodedSize &&
          packetCount == other.packetCount &&
          estimatedSeconds == other.estimatedSeconds;
}
