// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/rx.dart';
import 'api/tx.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 217356223;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'sonic_share_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<RxSession> crateApiRxRxSessionNew({
    required int sampleRate,
    required String outputDir,
  });

  Future<RxSession> crateApiRxRxSessionNewWithProfile({
    required int sampleRate,
    required String outputDir,
    required bool robust,
    required int lane,
  });

  Future<List<MobileReceiveEvent>> crateApiRxRxSessionPushPcm16({
    required RxSession that,
    required List<int> pcm16Le,
  });

  Future<void> crateApiTxTxSessionCancel({required TxSession that});

  Future<TxSession> crateApiTxTxSessionFromData({
    required String name,
    String? contentType,
    required List<int> data,
  });

  Future<TxSession> crateApiTxTxSessionFromDataWithProfile({
    required String name,
    String? contentType,
    required List<int> data,
    required bool robust,
    required int lane,
  });

  Future<TxSession> crateApiTxTxSessionFromFile({
    required String path,
    String? contentType,
  });

  Future<TxSession> crateApiTxTxSessionFromFileWithProfile({
    required String path,
    String? contentType,
    required bool robust,
    required int lane,
  });

  Future<TxInfo> crateApiTxTxSessionInfo({required TxSession that});

  Future<TxChunk> crateApiTxTxSessionNextPcmChunk({
    required TxSession that,
    required int maxSamples,
  });

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RxSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RxSession;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RxSessionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TxSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TxSession;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TxSessionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<RxSession> crateApiRxRxSessionNew({
    required int sampleRate,
    required String outputDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sampleRate, serializer);
          sse_encode_String(outputDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRxRxSessionNewConstMeta,
        argValues: [sampleRate, outputDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRxRxSessionNewConstMeta => const TaskConstMeta(
    debugName: "RxSession_new",
    argNames: ["sampleRate", "outputDir"],
  );

  @override
  Future<RxSession> crateApiRxRxSessionNewWithProfile({
    required int sampleRate,
    required String outputDir,
    required bool robust,
    required int lane,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sampleRate, serializer);
          sse_encode_String(outputDir, serializer);
          sse_encode_bool(robust, serializer);
          sse_encode_u_8(lane, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRxRxSessionNewWithProfileConstMeta,
        argValues: [sampleRate, outputDir, robust, lane],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRxRxSessionNewWithProfileConstMeta =>
      const TaskConstMeta(
        debugName: "RxSession_new_with_profile",
        argNames: ["sampleRate", "outputDir", "robust", "lane"],
      );

  @override
  Future<List<MobileReceiveEvent>> crateApiRxRxSessionPushPcm16({
    required RxSession that,
    required List<int> pcm16Le,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(pcm16Le, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mobile_receive_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRxRxSessionPushPcm16ConstMeta,
        argValues: [that, pcm16Le],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRxRxSessionPushPcm16ConstMeta =>
      const TaskConstMeta(
        debugName: "RxSession_push_pcm16",
        argNames: ["that", "pcm16Le"],
      );

  @override
  Future<void> crateApiTxTxSessionCancel({required TxSession that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTxTxSessionCancelConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxTxSessionCancelConstMeta =>
      const TaskConstMeta(debugName: "TxSession_cancel", argNames: ["that"]);

  @override
  Future<TxSession> crateApiTxTxSessionFromData({
    required String name,
    String? contentType,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(contentType, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTxTxSessionFromDataConstMeta,
        argValues: [name, contentType, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxTxSessionFromDataConstMeta =>
      const TaskConstMeta(
        debugName: "TxSession_from_data",
        argNames: ["name", "contentType", "data"],
      );

  @override
  Future<TxSession> crateApiTxTxSessionFromDataWithProfile({
    required String name,
    String? contentType,
    required List<int> data,
    required bool robust,
    required int lane,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(contentType, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_bool(robust, serializer);
          sse_encode_u_8(lane, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTxTxSessionFromDataWithProfileConstMeta,
        argValues: [name, contentType, data, robust, lane],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxTxSessionFromDataWithProfileConstMeta =>
      const TaskConstMeta(
        debugName: "TxSession_from_data_with_profile",
        argNames: ["name", "contentType", "data", "robust", "lane"],
      );

  @override
  Future<TxSession> crateApiTxTxSessionFromFile({
    required String path,
    String? contentType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_opt_String(contentType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTxTxSessionFromFileConstMeta,
        argValues: [path, contentType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxTxSessionFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "TxSession_from_file",
        argNames: ["path", "contentType"],
      );

  @override
  Future<TxSession> crateApiTxTxSessionFromFileWithProfile({
    required String path,
    String? contentType,
    required bool robust,
    required int lane,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_opt_String(contentType, serializer);
          sse_encode_bool(robust, serializer);
          sse_encode_u_8(lane, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTxTxSessionFromFileWithProfileConstMeta,
        argValues: [path, contentType, robust, lane],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxTxSessionFromFileWithProfileConstMeta =>
      const TaskConstMeta(
        debugName: "TxSession_from_file_with_profile",
        argNames: ["path", "contentType", "robust", "lane"],
      );

  @override
  Future<TxInfo> crateApiTxTxSessionInfo({required TxSession that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tx_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTxTxSessionInfoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxTxSessionInfoConstMeta =>
      const TaskConstMeta(debugName: "TxSession_info", argNames: ["that"]);

  @override
  Future<TxChunk> crateApiTxTxSessionNextPcmChunk({
    required TxSession that,
    required int maxSamples,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
            that,
            serializer,
          );
          sse_encode_u_32(maxSamples, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tx_chunk,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTxTxSessionNextPcmChunkConstMeta,
        argValues: [that, maxSamples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxTxSessionNextPcmChunkConstMeta =>
      const TaskConstMeta(
        debugName: "TxSession_next_pcm_chunk",
        argNames: ["that", "maxSamples"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RxSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RxSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TxSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TxSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession;

  @protected
  RxSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RxSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TxSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TxSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RxSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RxSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TxSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TxSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TxSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TxSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RxSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RxSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TxSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TxSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<MobileReceiveEvent> dco_decode_list_mobile_receive_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mobile_receive_event).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MobileReceiveEvent dco_decode_mobile_receive_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return MobileReceiveEvent(
      kind: dco_decode_String(arr[0]),
      id: dco_decode_String(arr[1]),
      name: dco_decode_opt_String(arr[2]),
      contentType: dco_decode_opt_String(arr[3]),
      path: dco_decode_opt_String(arr[4]),
      text: dco_decode_opt_String(arr[5]),
      message: dco_decode_opt_String(arr[6]),
      originalSize: dco_decode_opt_box_autoadd_u_64(arr[7]),
      completedGroups: dco_decode_opt_box_autoadd_u_32(arr[8]),
      totalGroups: dco_decode_opt_box_autoadd_u_32(arr[9]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  TxChunk dco_decode_tx_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TxChunk(
      pcm16Le: dco_decode_list_prim_u_8_strict(arr[0]),
      progress: dco_decode_f_64(arr[1]),
      packetIndex: dco_decode_u_32(arr[2]),
      packetCount: dco_decode_u_32(arr[3]),
      done: dco_decode_bool(arr[4]),
    );
  }

  @protected
  TxInfo dco_decode_tx_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TxInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      contentType: dco_decode_String(arr[2]),
      originalSize: dco_decode_u_64(arr[3]),
      encodedSize: dco_decode_u_64(arr[4]),
      packetCount: dco_decode_u_32(arr[5]),
      estimatedSeconds: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  RxSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RxSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TxSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TxSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RxSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RxSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TxSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TxSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TxSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TxSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RxSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RxSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TxSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TxSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<MobileReceiveEvent> sse_decode_list_mobile_receive_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MobileReceiveEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mobile_receive_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MobileReceiveEvent sse_decode_mobile_receive_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_contentType = sse_decode_opt_String(deserializer);
    var var_path = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_originalSize = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_completedGroups = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_totalGroups = sse_decode_opt_box_autoadd_u_32(deserializer);
    return MobileReceiveEvent(
      kind: var_kind,
      id: var_id,
      name: var_name,
      contentType: var_contentType,
      path: var_path,
      text: var_text,
      message: var_message,
      originalSize: var_originalSize,
      completedGroups: var_completedGroups,
      totalGroups: var_totalGroups,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TxChunk sse_decode_tx_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pcm16Le = sse_decode_list_prim_u_8_strict(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_packetIndex = sse_decode_u_32(deserializer);
    var var_packetCount = sse_decode_u_32(deserializer);
    var var_done = sse_decode_bool(deserializer);
    return TxChunk(
      pcm16Le: var_pcm16Le,
      progress: var_progress,
      packetIndex: var_packetIndex,
      packetCount: var_packetCount,
      done: var_done,
    );
  }

  @protected
  TxInfo sse_decode_tx_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_originalSize = sse_decode_u_64(deserializer);
    var var_encodedSize = sse_decode_u_64(deserializer);
    var var_packetCount = sse_decode_u_32(deserializer);
    var var_estimatedSeconds = sse_decode_f_64(deserializer);
    return TxInfo(
      id: var_id,
      name: var_name,
      contentType: var_contentType,
      originalSize: var_originalSize,
      encodedSize: var_encodedSize,
      packetCount: var_packetCount,
      estimatedSeconds: var_estimatedSeconds,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    RxSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RxSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    TxSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TxSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    RxSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RxSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    TxSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TxSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    TxSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TxSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRxSession(
    RxSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RxSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTxSession(
    TxSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TxSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_mobile_receive_event(
    List<MobileReceiveEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mobile_receive_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mobile_receive_event(
    MobileReceiveEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.contentType, serializer);
    sse_encode_opt_String(self.path, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_opt_box_autoadd_u_64(self.originalSize, serializer);
    sse_encode_opt_box_autoadd_u_32(self.completedGroups, serializer);
    sse_encode_opt_box_autoadd_u_32(self.totalGroups, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_tx_chunk(TxChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.pcm16Le, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_u_32(self.packetIndex, serializer);
    sse_encode_u_32(self.packetCount, serializer);
    sse_encode_bool(self.done, serializer);
  }

  @protected
  void sse_encode_tx_info(TxInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_u_64(self.originalSize, serializer);
    sse_encode_u_64(self.encodedSize, serializer);
    sse_encode_u_32(self.packetCount, serializer);
    sse_encode_f_64(self.estimatedSeconds, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class RxSessionImpl extends RustOpaque implements RxSession {
  // Not to be used by end users
  RxSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RxSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RxSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RxSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RxSessionPtr,
  );

  Future<List<MobileReceiveEvent>> pushPcm16({required List<int> pcm16Le}) =>
      RustLib.instance.api.crateApiRxRxSessionPushPcm16(
        that: this,
        pcm16Le: pcm16Le,
      );
}

@sealed
class TxSessionImpl extends RustOpaque implements TxSession {
  // Not to be used by end users
  TxSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TxSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TxSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TxSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TxSessionPtr,
  );

  Future<void> cancel() =>
      RustLib.instance.api.crateApiTxTxSessionCancel(that: this);

  Future<TxInfo> info() =>
      RustLib.instance.api.crateApiTxTxSessionInfo(that: this);

  Future<TxChunk> nextPcmChunk({required int maxSamples}) => RustLib
      .instance
      .api
      .crateApiTxTxSessionNextPcmChunk(that: this, maxSamples: maxSamples);
}
